model_type: "xgboost"
test_size: 0.2
random_state: 42
target: "HeartDisease"

estimator:
  _target_: xgboost.XGBClassifier
  n_estimators: 100
  max_depth: 3
  learning_rate: 0.1
  scale_pos_weight: 5
  random_state: 42
  eval_metric: "logloss"
